# Generated by Django 2.1.7 on 2019-03-02 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("musr", "0002_auto_20190228_1547")]

    operations = [
        migrations.RenameField(
            model_name="post", old_name="Post_Id", new_name="post_id"
        ),
        migrations.RenameField(
            model_name="post", old_name="Song_Id", new_name="song_id"
        ),
        migrations.RemoveField(model_name="post", name="Original_Poster_Id"),
        migrations.AddField(
            model_name="post",
            name="original_poster",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="original_poster",
                to="musr.Profile",
            ),
        ),
    ]
