# Generated by Django 2.1.7 on 2019-03-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("musr", "0004_auto_20190305_1158")]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="picture",
            field=models.ImageField(
                blank=True,
                default="profile_images/default.jpg",
                upload_to="profile_images",
            ),
        )
    ]
